### ISSUE TITLE
Support type system in cases

### ISSUE THREAD

**Issue by daenney** [voxpupuli/puppet-lint-unquoted_string-check#1]
With Puppet 4's Type system you can have unquoted strings in case statements, like so:

```puppet
case $value {
  Integer: { notice('yes int')}
  Array: { notice('yes array')}
  'Debian': { notice('this is Sparta')}
  default: { notice('something else')}
}
```

However, this will cause the plugin to furiously complain about the first 2 lines in the case statement as it considers that they need to be quoted but in this case will actually do a type check. Line 3 will be OK since that's quoted so will check the assigned value of `$value` and compare to that instead.

Any of the types listed [here](https://github.com/puppetlabs/puppet-specifications/blob/master/language/types_values_variables.md) should be allowed unquoted in a `case` statement.

**Comment by igalic** [comment]
:+1: make it so, number one.

**Comment by daenney** [comment]
I don't think it's super-trivial unfortunately. From what I gather it would require puppet-lint to recognise certain strings as type annotations so you can filter out based on `token.type == :TYPE` or something like that. There's probably ways to hardcode it in this plugin but that would be a bit meh.

@raphink @mcanevet Any thoughts?

**Comment by mcanevet** [comment]
@daenney you're right, puppet-lint need to be patched to support future parser's Puppet Types. In the mean time I have a very ugly patch for your issue...

**Comment by mcanevet** [comment]
This may ease things : https://github.com/rodjek/puppet-lint/pull/435

**Comment by raphink** [comment]
I'm in favor of waiting for rodjek/puppet-lint#435 to be merged so we can leverage it safely.

**Comment by daenney** [comment]
I'm wish I could say the same but I'm not. If you look at puppet-lint nothing has happened since April which honestly doesn't give me much hope of this patch landing there anytime soon.

Since this is currently incorrectly flagging valid constructs in Puppet 4 manifests I think we should fix it here in the mean time.

**Comment by raphink** [comment]
Yes, @rodjek has little time for these projects. @davids now has commit rights on rspec-puppet, which helps tons, but for puppet-lint, not much has been done. It would be great if either someone from PL had rights on it, or if it were transferred to puppet-community.

**Comment by mcanevet** [comment]
@daenney your new avatar does not help to follow a discussion with @raphink in it... :-)

**Comment by igalic** [comment]
haah

**Comment by daenney** [comment]
@mcanevet What new avatar? :stuck_out_tongue:

**Comment by igalic** [comment]
@daenney soooo much better :+1: :100:

**Comment by raphink** [comment]
I got a screenshot this morning, just in case!

**Comment by raphink** [comment]
@igalic what does that mean about mine then? :stuck_out_tongue:

**Comment by daenney** [comment]
We have slightly derailed the topic :stuck_out_tongue_closed_eyes:.

**Comment by raphink** [comment]
For the record then, a screenshot from https://github.com/puppetlabs/puppetlabs_spec_helper/pull/89:

![screenshot from 2015-08-04 11 47 32](https://cloud.githubusercontent.com/assets/650430/9060668/23cb5a20-3ab6-11e5-8d76-488a1df8a33a.png)

**Comment by igalic** [comment]
excellent @raphink/@daenney.

now, let's get back on track.

what, exactly, is the point of strict variables?
and why do we keep moving it one release further down with each iteration?

**Comment by raphink** [comment]
The point is to avoid out of scope variables imo, and using it and enforcing it has greatly helped us, especially when migrating to Puppet 3.

**Comment by daenney** [comment]
This PR has nothing to do with strict variables so please leave that discussion where it's supposed to be, in the PR on puppetlabs_spec_helper. This is about correctly supporting Type matchers in case statements.

**Comment by raphink** [comment]
Yes, that's right. Got side-tracked by the comment. So here, we're just waiting for @mcanevet's patch to puppet-lint to be merged…

**Comment by mcanevet** [comment]
This may take a while unfortunately...

**Comment by daenney** [comment]
I'm inclined to say we should merge the ugly patch because I doubt we'll get a PR accepted and released before Puppetconf otherwise :disappointed:.

**Comment by igalic** [comment]
i'm guessing unlike rspec, there's no people with merge access to lint?

**Comment by daenney** [comment]
As far as I can see from the PR history the owner is the only one to have merged PRs.
